// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: userServer.proto

package user

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type RequestHello struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" form:"name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestHello) Reset()         { *m = RequestHello{} }
func (m *RequestHello) String() string { return proto.CompactTextString(m) }
func (*RequestHello) ProtoMessage()    {}
func (*RequestHello) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec48fc4981894f51, []int{0}
}
func (m *RequestHello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHello.Unmarshal(m, b)
}
func (m *RequestHello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHello.Marshal(b, m, deterministic)
}
func (m *RequestHello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHello.Merge(m, src)
}
func (m *RequestHello) XXX_Size() int {
	return xxx_messageInfo_RequestHello.Size(m)
}
func (m *RequestHello) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHello.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHello proto.InternalMessageInfo

func (m *RequestHello) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ResponseHello struct {
	Str                  string   `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseHello) Reset()         { *m = ResponseHello{} }
func (m *ResponseHello) String() string { return proto.CompactTextString(m) }
func (*ResponseHello) ProtoMessage()    {}
func (*ResponseHello) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec48fc4981894f51, []int{1}
}
func (m *ResponseHello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHello.Unmarshal(m, b)
}
func (m *ResponseHello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHello.Marshal(b, m, deterministic)
}
func (m *ResponseHello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHello.Merge(m, src)
}
func (m *ResponseHello) XXX_Size() int {
	return xxx_messageInfo_ResponseHello.Size(m)
}
func (m *ResponseHello) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHello.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHello proto.InternalMessageInfo

func (m *ResponseHello) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestHello)(nil), "user.RequestHello")
	proto.RegisterType((*ResponseHello)(nil), "user.ResponseHello")
}

func init() { proto.RegisterFile("userServer.proto", fileDescriptor_ec48fc4981894f51) }

var fileDescriptor_ec48fc4981894f51 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x2d, 0x4e, 0x2d,
	0x0a, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0x89,
	0x48, 0xe9, 0xa6, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0xa7, 0xe7, 0xa7,
	0xe7, 0xeb, 0x83, 0x25, 0x93, 0x4a, 0xd3, 0xc0, 0x3c, 0x30, 0x07, 0xcc, 0x82, 0x68, 0x52, 0x32,
	0xe6, 0xe2, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xf1, 0x48, 0xcd, 0xc9, 0xc9, 0x17, 0x52,
	0xe6, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x74, 0xe2, 0xff, 0x74,
	0x4f, 0x9e, 0x3b, 0x2d, 0xbf, 0x28, 0xd7, 0x4a, 0x09, 0x24, 0xaa, 0x14, 0x04, 0x96, 0x54, 0x52,
	0xe4, 0xe2, 0x0d, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x85, 0xe8, 0x12, 0xe0, 0x62, 0x2e,
	0x2e, 0x29, 0x82, 0x68, 0x0a, 0x02, 0x31, 0x8d, 0xac, 0xb9, 0x58, 0x42, 0x8b, 0x53, 0x8b, 0x84,
	0x8c, 0xb9, 0x38, 0x82, 0x13, 0x2b, 0x21, 0xaa, 0x84, 0xf4, 0x40, 0x2e, 0xd4, 0x43, 0xb6, 0x4f,
	0x4a, 0x18, 0x26, 0x86, 0x64, 0x9c, 0x13, 0x7b, 0x14, 0xab, 0x3e, 0x48, 0x38, 0x89, 0x0d, 0xec,
	0x48, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x46, 0xee, 0x39, 0xed, 0x00, 0x00, 0x00,
}
