// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/long250038728/web/application/agent/internal/domain"
	"github.com/long250038728/web/application/agent/internal/handles"
	"github.com/long250038728/web/application/agent/internal/repository"
	"github.com/long250038728/web/application/agent/internal/service"
	"github.com/long250038728/web/tool/app"
)

// Injectors from wire.go:

func InitHandles(util *app.Util) *handles.Handles {
	agent := repository.NewAgentRepository(util)
	domainAgent := domain.NewAgentDomain(agent)
	serviceAgent := service.NewService(domainAgent)
	handlesHandles := handles.NewHandles(serviceAgent, util)
	return handlesHandles
}
