apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-v1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
      version: v1
  template:
    metadata:
      labels:
        app: user
        version: v1
    spec:
      containers:
        - name: user-container
          image: ccr.ccs.tencentyun.com/linl/user:v1
          ports:
            - containerPort: 8001
            - containerPort: 9001

---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: normal
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      name: user-port-8001
    - protocol: TCP
      port: 9001
      targetPort: 9001
      name: user-port-9001
  type: ClusterIP