ip: ""
env: dev    # 可用于环境的区分
grpc: local # 支持local,k8s,register
servers:
  user:
    http_port: 8001
    grpc_port: 9001
  order:
    http_port: 8002
    grpc_port: 9002
  authorization:
    http_port: 8003
    grpc_port: 9003