ip: ""
env: dev    # 可用于环境的区分
rpc_type: local # 支持local,kubernetes,register
servers:
  user:
    http_port: 8001
    grpc_port: 9001
  order:
    http_port: 8002
    grpc_port: 9002
  auth:
    http_port: 8003
    grpc_port: 9003
  agent:
    http_port: 8011
    grpc_port: 9011