FROM golang:1.20 as builder
WORKDIR /opt/app
COPY  ./app .
ENV GOPROXY=https://goproxy.io,direct
RUN cd  /opt/app/web/application/user/cmd/ && \
    go build -o main main.go

FROM ubuntu:latest
WORKDIR /opt/app
COPY --from=builder /opt/app/web/application/user/cmd/main /opt/app/main
EXPOSE 8090 8092
CMD ["/opt/app/main"]