// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wrie

import (
	"github.com/long250038728/web/application/agent/internal/domain"
	"github.com/long250038728/web/application/agent/internal/repository"
	"github.com/long250038728/web/application/agent/internal/service"
	"github.com/long250038728/web/tool/app"
)

// Injectors from wire.go:

func InitServer(util *app.Util) *service.Agent {
	agentRepository := repository.NewAgentRepository(util)
	agentDomain := domain.NewAgentDomain(agentRepository)
	agentService := service.NewService(agentDomain)
	return agentService
}
