FROM golang:1.20 as mod
WORKDIR /app
COPY  ./go.mod ./
COPY  ./go.sum ./
ENV GOPROXY=https://goproxy.io,direct
RUN go mod download

FROM mod as builder
WORKDIR /app
COPY  ./app .
ENV GOPROXY=https://goproxy.io,direct
RUN cd  /app/application/user/cmd && go build -o main main.go

FROM ubuntu:latest
WORKDIR /opt/app
COPY --from=builder /app/application/user/cmd/main /opt/app/main
COPY --from=builder /app/config /opt/app/config
EXPOSE 8001 9001
CMD ["/opt/app/main"]