apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-job
spec:
  schedule: '*/1 * * * *'
  jobTemplate: 
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - image: nginx
            name: job
            imagePullPolicy: IfNotPresent
            command:
            - bin/echo
            args:
            - "hello world"