// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: agent.proto

package agent

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type EventsRequest struct {
	Ns                   string   `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
	Resource             string   `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventsRequest) Reset()         { *m = EventsRequest{} }
func (m *EventsRequest) String() string { return proto.CompactTextString(m) }
func (*EventsRequest) ProtoMessage()    {}
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}
func (m *EventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsRequest.Unmarshal(m, b)
}
func (m *EventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsRequest.Marshal(b, m, deterministic)
}
func (m *EventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsRequest.Merge(m, src)
}
func (m *EventsRequest) XXX_Size() int {
	return xxx_messageInfo_EventsRequest.Size(m)
}
func (m *EventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventsRequest proto.InternalMessageInfo

func (m *EventsRequest) GetNs() string {
	if m != nil {
		return m.Ns
	}
	return ""
}

func (m *EventsRequest) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

type EventsResponse struct {
	Event                []string `protobuf:"bytes,1,rep,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventsResponse) Reset()         { *m = EventsResponse{} }
func (m *EventsResponse) String() string { return proto.CompactTextString(m) }
func (*EventsResponse) ProtoMessage()    {}
func (*EventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}
func (m *EventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsResponse.Unmarshal(m, b)
}
func (m *EventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsResponse.Marshal(b, m, deterministic)
}
func (m *EventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsResponse.Merge(m, src)
}
func (m *EventsResponse) XXX_Size() int {
	return xxx_messageInfo_EventsResponse.Size(m)
}
func (m *EventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventsResponse proto.InternalMessageInfo

func (m *EventsResponse) GetEvent() []string {
	if m != nil {
		return m.Event
	}
	return nil
}

type LogsRequest struct {
	Ns                   string   `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Container            string   `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogsRequest) Reset()         { *m = LogsRequest{} }
func (m *LogsRequest) String() string { return proto.CompactTextString(m) }
func (*LogsRequest) ProtoMessage()    {}
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{2}
}
func (m *LogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogsRequest.Unmarshal(m, b)
}
func (m *LogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogsRequest.Marshal(b, m, deterministic)
}
func (m *LogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogsRequest.Merge(m, src)
}
func (m *LogsRequest) XXX_Size() int {
	return xxx_messageInfo_LogsRequest.Size(m)
}
func (m *LogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogsRequest proto.InternalMessageInfo

func (m *LogsRequest) GetNs() string {
	if m != nil {
		return m.Ns
	}
	return ""
}

func (m *LogsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LogsRequest) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

type LogsResponse struct {
	Log                  []string `protobuf:"bytes,1,rep,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogsResponse) Reset()         { *m = LogsResponse{} }
func (m *LogsResponse) String() string { return proto.CompactTextString(m) }
func (*LogsResponse) ProtoMessage()    {}
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{3}
}
func (m *LogsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogsResponse.Unmarshal(m, b)
}
func (m *LogsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogsResponse.Marshal(b, m, deterministic)
}
func (m *LogsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogsResponse.Merge(m, src)
}
func (m *LogsResponse) XXX_Size() int {
	return xxx_messageInfo_LogsResponse.Size(m)
}
func (m *LogsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogsResponse proto.InternalMessageInfo

func (m *LogsResponse) GetLog() []string {
	if m != nil {
		return m.Log
	}
	return nil
}

type ResourcesRequest struct {
	Ns                   string   `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
	Resource             string   `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourcesRequest) Reset()         { *m = ResourcesRequest{} }
func (m *ResourcesRequest) String() string { return proto.CompactTextString(m) }
func (*ResourcesRequest) ProtoMessage()    {}
func (*ResourcesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{4}
}
func (m *ResourcesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourcesRequest.Unmarshal(m, b)
}
func (m *ResourcesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourcesRequest.Marshal(b, m, deterministic)
}
func (m *ResourcesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourcesRequest.Merge(m, src)
}
func (m *ResourcesRequest) XXX_Size() int {
	return xxx_messageInfo_ResourcesRequest.Size(m)
}
func (m *ResourcesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourcesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResourcesRequest proto.InternalMessageInfo

func (m *ResourcesRequest) GetNs() string {
	if m != nil {
		return m.Ns
	}
	return ""
}

func (m *ResourcesRequest) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

type ResourcesResponse struct {
	Resource             []string `protobuf:"bytes,1,rep,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourcesResponse) Reset()         { *m = ResourcesResponse{} }
func (m *ResourcesResponse) String() string { return proto.CompactTextString(m) }
func (*ResourcesResponse) ProtoMessage()    {}
func (*ResourcesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{5}
}
func (m *ResourcesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourcesResponse.Unmarshal(m, b)
}
func (m *ResourcesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourcesResponse.Marshal(b, m, deterministic)
}
func (m *ResourcesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourcesResponse.Merge(m, src)
}
func (m *ResourcesResponse) XXX_Size() int {
	return xxx_messageInfo_ResourcesResponse.Size(m)
}
func (m *ResourcesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourcesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResourcesResponse proto.InternalMessageInfo

func (m *ResourcesResponse) GetResource() []string {
	if m != nil {
		return m.Resource
	}
	return nil
}

func init() {
	proto.RegisterType((*EventsRequest)(nil), "agent.EventsRequest")
	proto.RegisterType((*EventsResponse)(nil), "agent.EventsResponse")
	proto.RegisterType((*LogsRequest)(nil), "agent.LogsRequest")
	proto.RegisterType((*LogsResponse)(nil), "agent.LogsResponse")
	proto.RegisterType((*ResourcesRequest)(nil), "agent.ResourcesRequest")
	proto.RegisterType((*ResourcesResponse)(nil), "agent.ResourcesResponse")
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_56ede974c0020f77) }

var fileDescriptor_56ede974c0020f77 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0x24, 0x1f, 0x0d, 0xcd, 0x54, 0x4b, 0x7d, 0x56, 0x5c, 0x82, 0x87, 0xb0, 0x07, 0xe9, 0xa9,
	0x01, 0xc5, 0x93, 0x50, 0x50, 0xf0, 0x26, 0x08, 0x39, 0x7a, 0x8b, 0x65, 0x89, 0x82, 0xee, 0xd6,
	0xec, 0xc6, 0x9f, 0xe5, 0x6f, 0x94, 0xec, 0x6e, 0x63, 0x5a, 0xf1, 0xd2, 0xdb, 0xce, 0x4c, 0xe6,
	0xcd, 0x7b, 0x43, 0x30, 0xa9, 0x6a, 0x21, 0xcd, 0x72, 0xd3, 0x28, 0xa3, 0x68, 0x64, 0x01, 0xbf,
	0xc5, 0xf1, 0xc3, 0x97, 0x90, 0x46, 0x97, 0xe2, 0xb3, 0x15, 0xda, 0xd0, 0x14, 0xa1, 0xd4, 0x2c,
	0xc8, 0x83, 0x45, 0x5a, 0x86, 0x52, 0x53, 0x86, 0x71, 0x23, 0xb4, 0x6a, 0x9b, 0xb5, 0x60, 0xa1,
	0x65, 0x7b, 0xcc, 0x2f, 0x31, 0xdd, 0x9a, 0xf5, 0x46, 0x49, 0x2d, 0x68, 0x8e, 0x91, 0xe8, 0x18,
	0x16, 0xe4, 0xd1, 0x22, 0x2d, 0x1d, 0xe0, 0x4f, 0x98, 0x3c, 0xaa, 0xfa, 0xdf, 0x08, 0x42, 0x2c,
	0xab, 0x8f, 0xed, 0x78, 0xfb, 0xa6, 0x0b, 0xa4, 0x6b, 0x25, 0x4d, 0xf5, 0x26, 0x45, 0xc3, 0x22,
	0x2b, 0xfc, 0x12, 0x3c, 0xc7, 0x91, 0x1b, 0xe8, 0x63, 0x67, 0x88, 0xde, 0x55, 0xed, 0x43, 0xbb,
	0x27, 0x5f, 0x61, 0x56, 0xfa, 0x35, 0x0f, 0x3a, 0xad, 0xc0, 0xc9, 0xc0, 0xef, 0x63, 0x86, 0x06,
	0x97, 0xd5, 0xe3, 0xab, 0xef, 0x00, 0xf1, 0x5d, 0x6b, 0x5e, 0xe9, 0x06, 0x89, 0x2b, 0x85, 0xe6,
	0x4b, 0x57, 0xf8, 0x4e, 0xc1, 0xd9, 0xd9, 0x1e, 0xeb, 0x67, 0x17, 0x88, 0xbb, 0x93, 0x88, 0xbc,
	0x3c, 0x28, 0x2c, 0x3b, 0xdd, 0xe1, 0xbc, 0x61, 0x85, 0xb4, 0xdf, 0x90, 0xce, 0xfd, 0x17, 0xfb,
	0x37, 0x67, 0xec, 0xaf, 0xe0, 0xfc, 0xf7, 0xe3, 0xe7, 0xa4, 0xb0, 0xda, 0x4b, 0x62, 0xff, 0x88,
	0xeb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x08, 0xdc, 0xa7, 0x77, 0x20, 0x02, 0x00, 0x00,
}
