apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order-container
          image: ubuntu:latest
          ports:
            - containerPort: 18002
            - containerPort: 19002

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 18002
      targetPort: 18002
      name: order-http-port-18002
    - protocol: TCP
      port: 19002
      targetPort: 19002
      name: order-grpc-port-19002
  type: ClusterIP