FROM golang:1.23.8 AS mod
WORKDIR /app
COPY  ./app/go.mod ./
COPY  ./app/go.sum ./
ENV GOPROXY=https://goproxy.io,direct
RUN go mod download

FROM mod AS builder
WORKDIR /app
COPY  ./app .
ENV GOPROXY=https://goproxy.io,direct
RUN cd  /app/application/auth/cmd && go build -o main main.go

FROM ubuntu:latest
ENV TZ=Asia/Shanghai
RUN apt-get update && \
    apt-get install -y tzdata && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone
WORKDIR /opt/app
COPY --from=builder /app/application/auth/cmd/main /opt/app/main
COPY --from=builder /app/config /opt/app/config
ENV CONFIG=/app/config
EXPOSE 18003 19003
CMD ["/opt/app/main",">>","log.txt"]